'use strict';

const mongoose = require('mongoose');

require('../models');

async function cleanAndSeedPlans() {
  try {
    const BoskitDistributorPlan = mongoose.model('boskit_distributor_plans');
    const BoskitPlanVersion = mongoose.model('boskit_plan_versions');

    // Remove legacy franchise named or test copy plans
    await BoskitDistributorPlan.deleteMany({
      $or: [
        { name: /franchise/i },
        { name: /Apex Multi-District/i },
        { plan_code: /COPY/i },
        { plan_code: /TEST/i },
        { plan_code: /BK-DIST-APEX/i },
      ],
    });

    // Clean standard plans
    const standardPlans = [
      {
        name: 'District Distributor Tier (Starter)',
        plan_code: 'BK-DIST-STARTER',
        short_description: 'Designed for single-district distributor operations with core solar equipment catalogue access.',
        description: 'Entry-level territorial distribution package providing single revenue district exclusivity, up to 15 registered dealers, and wholesale equipment procurement.',
        joining_fee_paise: 2500000,
        renewal_fee_paise: 1000000,
        tax_rate_percent: 18,
        is_tax_inclusive: false,
        gst_hsn_code: '998399',
        billing_type: 'annual_recurring',
        validity_value: 12,
        validity_unit: 'months',
        territory_type: 'district',
        allowed_territories_count: 1,
        is_territory_exclusive: true,
        dealer_allowed: true,
        max_dealers: 15,
        can_onboard_dealers: true,
        dealer_direct_activation: false,
        dealer_pricing_permission: false,
        dealer_uses_admin_slabs_only: true,
        allows_all_products: true,
        product_access_type: 'all',
        discount_percentage: 10,
        distributor_margin_slab_min: 8,
        distributor_margin_slab_max: 14,
        pricing_tier: 'Standard Wholesale Slab',
        can_see_mrp: true,
        can_sell_direct: true,
        can_generate_quotes: true,
        lead_access_tier: 'standard',
        leads_per_month: 25,
        inventory_visibility: 'full',
        can_reserve_stock: true,
        stock_reservation_hours: 48,
        min_order_value_paise: 0,
        credit_limit_paise: 0,
        benefits: [
          '1 Dedicated Revenue District Exclusivity Lock',
          'Up to 15 Registered Local Dealer Accounts',
          'Standard 8% - 14% Channel Margin Slab',
          'Full BOS Component & Inverter Whitelist Access',
          'Direct Manufacturer Warranty Dispatch',
          'Real-time Inventory Reservations (48h Hold)',
        ],
        dashboard_modules: {
          overview: true,
          territories: true,
          catalogue: true,
          pricing: true,
          inventory: true,
          orders: true,
          customers: true,
          dealers: true,
          dealer_onboarding: true,
          leads: true,
          sales_reports: true,
          margin_reports: true,
          documents: true,
          support: true,
          subscriptions: true,
        },
        is_popular: false,
        badge_text: 'District Scale Tier',
        sort_order: 1,
        status: 'published',
        is_active: true,
        current_version: 1,
      },
      {
        name: 'Multi-District Growth Tier (Professional)',
        plan_code: 'BK-DIST-GROWTH',
        short_description: 'Strategic regional distribution tier for multi-district growth and enhanced dealer capacity.',
        description: 'Mid-tier expansion package covering up to 3 districts with guaranteed exclusivity, 45 dealer accounts, VIP inventory allocation, and elevated margin slabs.',
        joining_fee_paise: 5000000,
        renewal_fee_paise: 2000000,
        tax_rate_percent: 18,
        is_tax_inclusive: false,
        gst_hsn_code: '998399',
        billing_type: 'annual_recurring',
        validity_value: 12,
        validity_unit: 'months',
        territory_type: 'multiple_districts',
        allowed_territories_count: 3,
        is_territory_exclusive: true,
        dealer_allowed: true,
        max_dealers: 45,
        can_onboard_dealers: true,
        dealer_direct_activation: true,
        dealer_pricing_permission: true,
        dealer_uses_admin_slabs_only: false,
        allows_all_products: true,
        product_access_type: 'all',
        discount_percentage: 15,
        distributor_margin_slab_min: 12,
        distributor_margin_slab_max: 18,
        pricing_tier: 'Professional Growth Slab',
        can_see_mrp: true,
        can_sell_direct: true,
        can_generate_quotes: true,
        lead_access_tier: 'priority',
        leads_per_month: 60,
        inventory_visibility: 'full',
        can_reserve_stock: true,
        stock_reservation_hours: 72,
        min_order_value_paise: 0,
        credit_limit_paise: 50000000,
        benefits: [
          '3 Contiguous Revenue Districts with Exclusivity Lock',
          'Up to 45 Authorized Local Dealer Accounts',
          'Higher Margin Slab: 12% – 18% Wholesale Margin',
          'Direct Factory Dispatch Hotline & Stock Reservation',
          'Priority Regional EPC & C&I Project Sizing Leads',
          'Direct Sub-Dealer Activation Privileges',
        ],
        dashboard_modules: {
          overview: true,
          territories: true,
          catalogue: true,
          pricing: true,
          inventory: true,
          orders: true,
          customers: true,
          dealers: true,
          dealer_onboarding: true,
          leads: true,
          sales_reports: true,
          margin_reports: true,
          documents: true,
          support: true,
          subscriptions: true,
        },
        is_popular: true,
        badge_text: 'Most Popular Distributor Plan',
        sort_order: 2,
        status: 'published',
        is_active: true,
        current_version: 1,
      },
      {
        name: 'State Enterprise Distributor (Apex)',
        plan_code: 'BK-DIST-STATE',
        short_description: 'Master state-level hub with unlimited regional fulfillment, VIP margins, and tender supply rights.',
        description: 'Apex state enterprise agreement providing master distribution rights across entire state territory, 150+ sub-dealers, customized wholesale price lists, and dedicated account management.',
        joining_fee_paise: 15000000,
        renewal_fee_paise: 5000000,
        tax_rate_percent: 18,
        is_tax_inclusive: false,
        gst_hsn_code: '998399',
        billing_type: 'annual_recurring',
        validity_value: 12,
        validity_unit: 'months',
        territory_type: 'state',
        allowed_territories_count: 1,
        is_territory_exclusive: true,
        dealer_allowed: true,
        max_dealers: 150,
        can_onboard_dealers: true,
        dealer_direct_activation: true,
        dealer_pricing_permission: true,
        dealer_uses_admin_slabs_only: false,
        allows_all_products: true,
        product_access_type: 'all',
        discount_percentage: 20,
        distributor_margin_slab_min: 16,
        distributor_margin_slab_max: 24,
        pricing_tier: 'State Apex Platinum Slab',
        can_see_mrp: true,
        can_sell_direct: true,
        can_generate_quotes: true,
        lead_access_tier: 'vip_exclusive',
        leads_per_month: 150,
        inventory_visibility: 'full',
        can_reserve_stock: true,
        stock_reservation_hours: 120,
        min_order_value_paise: 0,
        credit_limit_paise: 200000000,
        benefits: [
          'Entire State Territory Master Distribution Hub',
          'Up to 150 Registered District Dealers',
          'Maximum Wholesale Margin Slab: 16% – 24%',
          'Dedicated Warehouse Stock Hold & Account Executive',
          'Exclusive State Utility & Institutional Tender Access',
          'Full Margin & Sub-Dealer Slab Override Authority',
        ],
        dashboard_modules: {
          overview: true,
          territories: true,
          catalogue: true,
          pricing: true,
          inventory: true,
          orders: true,
          customers: true,
          dealers: true,
          dealer_onboarding: true,
          leads: true,
          sales_reports: true,
          margin_reports: true,
          documents: true,
          support: true,
          subscriptions: true,
        },
        is_popular: false,
        badge_text: 'State Enterprise Apex Tier',
        sort_order: 3,
        status: 'published',
        is_active: true,
        current_version: 1,
      },
    ];

    for (const pData of standardPlans) {
      const plan = await BoskitDistributorPlan.findOneAndUpdate(
        { plan_code: pData.plan_code },
        { $set: pData },
        { upsert: true, new: true }
      );

      await BoskitPlanVersion.findOneAndUpdate(
        { plan_id: plan._id, version_number: 1 },
        { $set: { snapshot: plan.toObject ? plan.toObject() : plan } },
        { upsert: true }
      );
    }

    console.log('✅ Cleaned and seeded 3 standard distributor tiers successfully.');
  } catch (error) {
    console.error('cleanAndSeedPlans Error:', error);
  }
}

module.exports = { cleanAndSeedPlans };
