/**
 * configModulesData.js
 *
 * Central Registry of all Configuration Modules across the entire project:
 * - SolarShop Configurations (All items from SolarShop menu)
 * - BDE Management & Sales Teams
 * - SolarKits Platform & Catalog
 * - Logistics, Fleet & Delivery Management
 * - Location, Clusters & Infrastructure
 * - System Settings, RBAC & Website CMS
 */

export const CONFIG_CATEGORIES = [
  { id: 'all', label: 'All Modules' },
  { id: 'solarshop', label: 'SolarShop' },
  { id: 'franchisee', label: 'Franchisee Mgmt' },
  { id: 'delivery', label: 'Delivery & Fleet' },
  { id: 'margin-quotes', label: 'Margins & Quotes' },
  { id: 'bde', label: 'BDE Management' },
  { id: 'solarkits', label: 'SolarKits Core' },
  { id: 'location', label: 'Location & Clusters' },
  { id: 'system', label: 'System & RBAC' },
];

export const CONFIG_MODULES = [
  // ──────────────────────────────────────────────────────────────────────────
  // 1. SOLARSHOP: EPC & KITS CONFIGURATIONS (From SolarShop Menu)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'ss-approve-epc',
    title: 'Approve New EPC',
    category: 'solarshop',
    categoryLabel: 'SolarShop',
    description: 'Review and approve pending EPC contractor applications and onboarding verification.',
    route: '/admin-panel/solar-shop/approve-new-epc',
    primaryAction: 'Approve EPCs',
    icon: 'FaUserCheck',
    isRegional: true,
    regionalContextHint: 'Filter EPC applicants by State and District.',
    badge: 'EPC Onboarding',
    keywords: ['epc', 'approve', 'new epc', 'contractors', 'verification', 'solar shop'],
  },
  {
    id: 'ss-combo-kits',
    title: 'Combo Kits',
    category: 'solarshop',
    categoryLabel: 'SolarShop',
    description: 'Configure standard combo kits, bundled solar packages, and equipment specifications.',
    route: '/admin-panel/solar-shop/combokit-configurations/combo-kits',
    primaryAction: 'Configure Combo Kits',
    icon: 'HiCube',
    isRegional: false,
    badge: 'Kits Catalog',
    keywords: ['combo kits', 'packages', 'bundles', 'solar shop', 'products', 'solar kit configurations'],
  },
  {
    id: 'ss-customize-kits',
    title: 'Customize Kits',
    category: 'solarshop',
    categoryLabel: 'SolarShop',
    description: 'Define allowed modular substitutions and customization options for SolarShop kits.',
    route: '/admin-panel/solar-shop/combokit-configurations/customize-kits',
    primaryAction: 'Customize Kits',
    icon: 'HiCube',
    isRegional: false,
    badge: 'Kits Customization',
    keywords: ['customize', 'kits', 'options', 'substitutions', 'modular', 'solar kit configurations'],
  },
  {
    id: 'ss-bulk-kits',
    title: 'Bulk Combo Kits',
    category: 'solarshop',
    categoryLabel: 'SolarShop',
    description: 'Configure bulk purchasing tiers, volume packages, and commercial volume pricing.',
    route: '/admin-panel/solar-shop/combokit-configurations/bulk-combo-kits',
    primaryAction: 'Manage Bulk Kits',
    icon: 'HiCube',
    isRegional: false,
    badge: 'Bulk Packages',
    keywords: ['bulk', 'wholesale', 'combo kits', 'volume', 'commercial', 'solar kit configurations'],
  },
  {
    id: 'ss-variants',
    title: 'Combo Kit Variants',
    category: 'solarshop',
    categoryLabel: 'SolarShop',
    description: 'Configure capacity variants (1kW, 2kW, 3kW, 5kW, 10kW) and battery/grid configurations.',
    route: '/admin-panel/solar-shop/combokit-configurations/combo-kit-variants',
    primaryAction: 'Configure Variants',
    icon: 'HiCube',
    isRegional: false,
    badge: 'Kit Variants',
    keywords: ['variants', 'capacity', 'kw', 'on-grid', 'off-grid', 'hybrid', 'solar kit configurations'],
  },
  {
    id: 'ss-pincode-delivery',
    title: 'Pincode Delivery Costs',
    category: 'solarshop',
    categoryLabel: 'SolarShop',
    description: 'Configure district and pincode-level delivery freight charges and serviceability rules.',
    route: '/admin-panel/solar-shop/combokit-configurations/pincode-delivery-costs',
    primaryAction: 'Set Pincode Rates',
    icon: 'FaTruck',
    isRegional: true,
    regionalContextHint: 'Delivery freight and pincode serviceability depends directly on District/Pincode.',
    badge: 'Regional Freight',
    keywords: ['pincode', 'delivery', 'freight', 'district', 'shipping', 'cost', 'serviceability', 'solar kit configurations'],
  },
  {
    id: 'ss-best-seller',
    title: 'Best Seller Configuration',
    category: 'solarshop',
    categoryLabel: 'SolarShop',
    description: 'Curate featured kits and best-seller badges displayed across the customer solar store.',
    route: '/admin-panel/solar-shop/combokit-configurations/best-seller',
    primaryAction: 'Configure Best Sellers',
    icon: 'FaAward',
    isRegional: false,
    badge: 'Merchandising',
    keywords: ['best seller', 'featured', 'popular', 'store front', 'badges', 'solar kit configurations'],
  },
  {
    id: 'ss-po-orders',
    title: 'PO Orders Management',
    category: 'solarshop',
    categoryLabel: 'SolarShop',
    description: 'View and manage Purchase Orders (PO) generated across regional warehouses and EPC buyers.',
    route: '/admin-panel/solar-shop/po-orders',
    primaryAction: 'View PO Orders',
    icon: 'FaFileInvoiceDollar',
    isRegional: true,
    regionalContextHint: 'Filter PO orders by warehouse location.',
    badge: 'Orders',
    keywords: ['po orders', 'purchase orders', 'procurement', 'warehouse po', 'solar shop orders'],
  },
  {
    id: 'ss-loose-orders',
    title: 'Loose Orders Management',
    category: 'solarshop',
    categoryLabel: 'SolarShop',
    description: 'Manage loose component orders, individual panel/inverter sales, and dispatch queues.',
    route: '/admin-panel/solar-shop/loose-orders',
    primaryAction: 'View Loose Orders',
    icon: 'FaBoxes',
    isRegional: true,
    regionalContextHint: 'Filter loose component orders by warehouse.',
    badge: 'Orders',
    keywords: ['loose orders', 'individual parts', 'components', 'dispatch', 'solar shop orders'],
  },
  {
    id: 'ss-wh-kit-activations',
    title: 'Warehouse Kit Activations',
    category: 'solarshop',
    categoryLabel: 'SolarShop',
    description: 'Toggle which kits and SKUs are active and stockable in specific regional warehouses.',
    route: '/admin-panel/solar-shop/warehouse-kit-activations',
    primaryAction: 'Activate Warehouse Kits',
    icon: 'FaToggleOn',
    isRegional: true,
    regionalContextHint: 'Enable or disable kit availability per regional warehouse hub.',
    badge: 'Regional Stock',
    keywords: ['warehouse', 'kit activation', 'availability', 'stocking', 'inventory toggle', 'warehouse kit activations'],
  },
  {
    id: 'ss-order-settings',
    title: 'Order Management Settings',
    category: 'solarshop',
    categoryLabel: 'SolarShop',
    description: 'Configure order processing workflows, checkout rules, and order thresholds.',
    route: '/admin-panel/solar-shop/order-management-settings',
    primaryAction: 'Configure Orders',
    icon: 'FiSliders',
    isRegional: false,
    badge: 'Order Rules',
    keywords: ['order management settings', 'order settings', 'checkout', 'rules', 'order processing'],
  },
  {
    id: 'ss-offers-mgmt',
    title: 'Offers Management',
    category: 'solarshop',
    categoryLabel: 'SolarShop',
    description: 'Configure seasonal offers, coupon codes, and promotional campaigns.',
    route: '/admin-panel/solar-shop/order-management-settings/offers',
    primaryAction: 'Manage Offers',
    icon: 'HiCube',
    isRegional: false,
    badge: 'Promotions',
    keywords: ['offers management', 'coupons', 'discounts', 'campaigns', 'order management settings'],
  },
  {
    id: 'ss-checkout-cart',
    title: 'Checkout Cart Settings',
    category: 'solarshop',
    categoryLabel: 'SolarShop',
    description: 'Configure minimum order values, cart timeout, deposit requirements, and checkout limits.',
    route: '/admin-panel/solar-shop/order-management-settings/checkout-cart',
    primaryAction: 'Configure Cart',
    icon: 'HiCube',
    isRegional: false,
    badge: 'Cart Rules',
    keywords: ['checkout cart settings', 'cart', 'minimum order', 'payment terms', 'order management settings'],
  },
  {
    id: 'ss-service-tickets',
    title: 'Service Tickets Admin',
    category: 'solarshop',
    categoryLabel: 'SolarShop',
    description: 'Manage post-sale customer service tickets, warranty claims, and kit replacement requests.',
    route: '/admin-panel/solar-shop/service-tickets',
    primaryAction: 'Manage Tickets',
    icon: 'FiTool',
    isRegional: true,
    regionalContextHint: 'Filter service tickets by State, District, and Franchisee.',
    badge: 'Support & Warranty',
    keywords: ['service tickets', 'warranty claims', 'repairs', 'replacements', 'customer support'],
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 2. SOLARSHOP: DELIVERY MANAGEMENT (From SolarShop Menu)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'del-vehicle-master',
    title: '1. Vehicle Master (Catalog)',
    category: 'delivery',
    categoryLabel: 'Delivery & Fleet',
    description: 'Configure vehicle types (Tata Ace, 14ft, 22ft Trucks), load capacities, and volume metrics.',
    route: '/admin-panel/solar-shop/delivery-management/vehicle-master',
    primaryAction: 'Manage Fleet Types',
    icon: 'FaTruck',
    isRegional: false,
    badge: 'Fleet Master',
    keywords: ['vehicle master', 'trucks', 'tata ace', 'fleet', 'transport', 'capacity', 'delivery management'],
  },
  {
    id: 'del-transport-vendors',
    title: '2. Transport Vendors',
    category: 'delivery',
    categoryLabel: 'Delivery & Fleet',
    description: 'Manage 3PL logistics partners, freight transporters, driver contacts, and vendor contracts.',
    route: '/admin-panel/solar-shop/delivery-management/providers',
    primaryAction: 'Manage Vendors',
    icon: 'FiUsers',
    isRegional: true,
    regionalContextHint: 'Vendors operate within specific state and interstate delivery routes.',
    badge: 'Regional Vendors',
    keywords: ['transport vendors', '3pl', 'logistics partners', 'carriers', 'transporters', 'delivery management'],
  },
  {
    id: 'del-fleet-vehicles',
    title: '3. Live Fleet & Vehicles',
    category: 'delivery',
    categoryLabel: 'Delivery & Fleet',
    description: 'Manage physical vehicles, registration numbers, driver assignments, and active GPS units.',
    route: '/admin-panel/solar-shop/delivery-management/fleet',
    primaryAction: 'Manage Live Fleet',
    icon: 'FaTruck',
    isRegional: false,
    badge: 'Active Fleet',
    keywords: ['live fleet', 'vehicles', 'drivers', 'registration', 'gps', 'delivery management'],
  },
  {
    id: 'del-kit-weights',
    title: '4. ComboKit Weight Master',
    category: 'delivery',
    categoryLabel: 'Delivery & Fleet',
    description: 'Configure kit weight parameters, volumetric dimensions, and freight weight calculations.',
    route: '/admin-panel/solar-shop/delivery-management/kit-weights',
    primaryAction: 'Configure Weights',
    icon: 'HiCube',
    isRegional: false,
    badge: 'Weight Master',
    keywords: ['combokit weight master', 'kit weights', 'volumetric weight', 'freight weight', 'delivery management'],
  },
  {
    id: 'del-cost-settings',
    title: '5. Delivery Cost Settings',
    category: 'delivery',
    categoryLabel: 'Delivery & Fleet',
    description: 'Configure base freight charges, per-km rates, toll formulas, and unloading surcharges.',
    route: '/admin-panel/solar-shop/delivery-management/cost-settings',
    primaryAction: 'Configure Freight Rates',
    icon: 'FiDollarSign',
    isRegional: true,
    regionalContextHint: 'Base freight and per-km formulas vary per state and terrain.',
    badge: 'Regional Freight',
    keywords: ['delivery cost settings', 'freight rates', 'shipping cost', 'per km', 'toll', 'delivery management'],
  },
  {
    id: 'del-routes',
    title: '6. Route & Consolidation',
    category: 'delivery',
    categoryLabel: 'Delivery & Fleet',
    description: 'Configure dispatch routes, delivery consolidation hubs, and transit time SLAs.',
    route: '/admin-panel/solar-shop/delivery-management/routes',
    primaryAction: 'Configure Routes',
    icon: 'FiSliders',
    isRegional: true,
    regionalContextHint: 'Routes link central warehouses to district delivery clusters.',
    badge: 'Regional Routes',
    keywords: ['route and consolidation', 'routes', 'consolidation', 'transit', 'sla', 'delivery management'],
  },
  {
    id: 'del-dashboard',
    title: '7. Delivery Dashboard & Analytics',
    category: 'delivery',
    categoryLabel: 'Delivery & Fleet',
    description: 'Track fleet movement, active dispatches, on-time delivery rates, and freight expense analytics.',
    route: '/admin-panel/solar-shop/delivery-management/dashboard',
    primaryAction: 'View Delivery Dash',
    icon: 'FiBarChart2',
    isRegional: true,
    regionalContextHint: 'Filter delivery performance metrics by State and District.',
    badge: 'Logistics Analytics',
    keywords: ['delivery dashboard', 'fleet analytics', 'logistics dashboard', 'delivery management'],
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 3. SOLARSHOP: MARGIN & COMMISSION (From SolarShop Menu)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'mc-warehouse-margins',
    title: 'Warehouse Margins',
    category: 'margin-quotes',
    categoryLabel: 'Margins & Quotes',
    description: 'Configure warehouse-specific profit margins and markup percentages across regional hubs.',
    route: '/admin-panel/solar-shop/company-margin',
    primaryAction: 'Configure Margins',
    icon: 'FaPercent',
    isRegional: true,
    regionalContextHint: 'Margins are customized per Warehouse location & State.',
    badge: 'Regional Margin',
    keywords: ['warehouse margins', 'margin and commission', 'markup', 'warehouse', 'state', 'profit', 'pricing'],
  },
  {
    id: 'mc-offers',
    title: 'Offers & Discounts',
    category: 'margin-quotes',
    categoryLabel: 'Margins & Quotes',
    description: 'Manage margin-level promotional discounts, coupon codes, and special campaigns.',
    route: '/admin-panel/solar-shop/company-margin/offers',
    primaryAction: 'Manage Offers',
    icon: 'FiTag',
    isRegional: false,
    badge: 'Promotions',
    keywords: ['offers and discounts', 'discounts', 'coupons', 'promotions', 'margin and commission'],
  },
  {
    id: 'mc-goals',
    title: 'Company Goals',
    category: 'margin-quotes',
    categoryLabel: 'Margins & Quotes',
    description: 'Set company-wide revenue, order volume, and gross margin targets for leadership dashboards.',
    route: '/admin-panel/solar-shop/company-margin/goals',
    primaryAction: 'Set Company Goals',
    icon: 'FiTarget',
    isRegional: false,
    badge: 'Targets',
    keywords: ['company goals', 'targets', 'revenue', 'company', 'milestones', 'margin and commission'],
  },
  {
    id: 'mc-analytics',
    title: 'Margin Analytics',
    category: 'margin-quotes',
    categoryLabel: 'Margins & Quotes',
    description: 'Analyze realized gross margins, discount impacts, and warehouse profitability trends.',
    route: '/admin-panel/solar-shop/company-margin/analytics',
    primaryAction: 'View Margin Analytics',
    icon: 'FiBarChart2',
    isRegional: true,
    regionalContextHint: 'View margin performance breakdown by State & Warehouse.',
    badge: 'Margin Analytics',
    keywords: ['margin analytics', 'profitability', 'gross margins', 'discount impact', 'margin and commission'],
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 4. SOLARSHOP: FRANCHISEE MANAGEMENT (From SolarShop Menu)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'fm-leads',
    title: 'Franchisee Leads',
    category: 'franchisee',
    categoryLabel: 'Franchisee Mgmt',
    description: 'Manage incoming prospective franchisee inquiries, outreach status, and qualification pipeline.',
    route: '/admin-panel/solar-shop/reseller-management/leads',
    primaryAction: 'View Leads',
    icon: 'FiFileText',
    isRegional: true,
    regionalContextHint: 'Filter franchisee leads by State and District.',
    badge: 'Acquisition',
    keywords: ['franchisee leads', 'leads', 'prospects', 'inquiries', 'reseller management'],
  },
  {
    id: 'fm-accounts',
    title: 'Franchisee Accounts',
    category: 'franchisee',
    categoryLabel: 'Franchisee Mgmt',
    description: 'Directory of all active and onboarding Franchisee accounts, owners, and contact profiles.',
    route: '/admin-panel/solar-shop/reseller-management/resellers',
    primaryAction: 'View Accounts',
    icon: 'FiUsers',
    isRegional: true,
    regionalContextHint: 'Filter franchisee accounts by State and District.',
    badge: 'Accounts',
    keywords: ['franchisee accounts', 'resellers', 'directory', 'stores', 'franchisee management'],
  },
  {
    id: 'fm-plans',
    title: 'Franchisee Plans',
    category: 'franchisee',
    categoryLabel: 'Franchisee Mgmt',
    description: 'Setup and configure Franchisee subscription tiers, deposit rules, and package entitlements.',
    route: '/admin-panel/solar-shop/reseller-management/plans',
    primaryAction: 'Manage Plans',
    icon: 'HiCube',
    isRegional: false,
    badge: 'Subscription Tiers',
    keywords: ['franchisee plans', 'subscription', 'tiers', 'deposit', 'reseller plans', 'franchisee management'],
  },
  {
    id: 'fm-settings',
    title: 'Franchisee Settings',
    category: 'franchisee',
    categoryLabel: 'Franchisee Mgmt',
    description: 'Configure global franchisee operational rules, minimum quarterly commitments, and terms.',
    route: '/admin-panel/solar-shop/reseller-management/franchise-settings',
    primaryAction: 'Franchisee Settings',
    icon: 'FiSliders',
    isRegional: false,
    badge: 'Governance',
    keywords: ['franchisee settings', 'operational rules', 'commitments', 'franchisee management'],
  },
  {
    id: 'fm-performance',
    title: 'Performance Tracker',
    category: 'franchisee',
    categoryLabel: 'Franchisee Mgmt',
    description: 'Track individual franchisee target vs achievement, kits sold, and growth milestones.',
    route: '/admin-panel/solar-shop/reseller-management/fpo/performance',
    primaryAction: 'View Tracker',
    icon: 'FiBarChart2',
    isRegional: true,
    regionalContextHint: 'Filter performance rankings by State and District.',
    badge: 'Performance',
    keywords: ['performance tracker', 'fpo performance', 'target vs achievement', 'franchisee management'],
  },
  {
    id: 'fm-commission-settings',
    title: 'Commission Settings',
    category: 'franchisee',
    categoryLabel: 'Franchisee Mgmt',
    description: 'Define franchisee sales commission slabs, payout schedules, and performance bonuses.',
    route: '/admin-panel/solar-shop/reseller-management/commission-settings',
    primaryAction: 'Set Commissions',
    icon: 'FiDollarSign',
    isRegional: false,
    badge: 'Commission Rules',
    keywords: ['commission settings', 'franchisee commission', 'payout', 'slabs', 'bonuses', 'franchisee management'],
  },
  {
    id: 'fm-commission-ledger',
    title: 'Commission Ledger',
    category: 'franchisee',
    categoryLabel: 'Franchisee Mgmt',
    description: 'Audit trail of all commission accruals, verified payouts, TDS deductions, and balances.',
    route: '/admin-panel/solar-shop/reseller-management/commission-ledger',
    primaryAction: 'View Ledger',
    icon: 'FiFileText',
    isRegional: true,
    regionalContextHint: 'Audit payouts per franchisee in State and District.',
    badge: 'Accounting',
    keywords: ['commission ledger', 'ledger', 'payout history', 'tds', 'franchisee management'],
  },
  {
    id: 'fm-store-setup',
    title: 'Store Setup & Operations',
    category: 'franchisee',
    categoryLabel: 'Franchisee Mgmt',
    description: 'Manage physical franchisee store readiness, branding assets, signage, and launch checklists.',
    route: '/admin-panel/solar-shop/reseller-management/store-setup',
    primaryAction: 'Configure Stores',
    icon: 'FaStore',
    isRegional: true,
    regionalContextHint: 'Franchisee physical stores mapped to district and city locations.',
    badge: 'Physical Stores',
    keywords: ['store setup & operations', 'store setup', 'franchisee store', 'physical store', 'branding', 'district'],
  },
  {
    id: 'fm-territories',
    title: 'Territories',
    category: 'franchisee',
    categoryLabel: 'Franchisee Mgmt',
    description: 'Configure franchisee territorial boundaries, pincode exclusivity, and authorized zones.',
    route: '/admin-panel/solar-shop/reseller-management/territories',
    primaryAction: 'Manage Territories',
    icon: 'FiMapPin',
    isRegional: true,
    regionalContextHint: 'Map exclusive sales territories to specific Districts and Pincodes.',
    badge: 'Territorial Scope',
    keywords: ['territories', 'franchisee territories', 'exclusivity', 'pincode mapping', 'franchisee management'],
  },
  {
    id: 'fm-prod-auth',
    title: 'Product Authorization',
    category: 'franchisee',
    categoryLabel: 'Franchisee Mgmt',
    description: 'Authorize which product lines and kit types individual franchisees are licensed to sell.',
    route: '/admin-panel/solar-shop/reseller-management/product-auth',
    primaryAction: 'Authorize Products',
    icon: 'FiPackage',
    isRegional: false,
    badge: 'Catalog Permissions',
    keywords: ['product authorization', 'authorization', 'licensed kits', 'franchisee management'],
  },
  {
    id: 'fm-epc-buyers',
    title: 'Franchisee EPC Buyers',
    category: 'franchisee',
    categoryLabel: 'Franchisee Mgmt',
    description: 'Manage EPC contractors affiliated with and purchasing through specific franchisee stores.',
    route: '/admin-panel/solar-shop/reseller-management/epc-buyers',
    primaryAction: 'View EPC Buyers',
    icon: 'FaUserCheck',
    isRegional: true,
    regionalContextHint: 'Filter affiliated EPC buyers by State and District.',
    badge: 'Contractor Network',
    keywords: ['franchisee epc buyers', 'epc buyers', 'contractors', 'franchisee management'],
  },
  {
    id: 'fm-orders',
    title: 'Franchisee Orders',
    category: 'franchisee',
    categoryLabel: 'Franchisee Mgmt',
    description: 'Manage sales orders placed directly by franchisees for store inventory and client fulfillment.',
    route: '/admin-panel/solar-shop/reseller-management/orders',
    primaryAction: 'View Orders',
    icon: 'FaFileInvoiceDollar',
    isRegional: true,
    regionalContextHint: 'Filter franchisee orders by State and District.',
    badge: 'Franchise Orders',
    keywords: ['franchisee orders', 'orders', 'store orders', 'reseller management'],
  },
  {
    id: 'fm-wallet',
    title: 'Earnings & Settlement',
    category: 'franchisee',
    categoryLabel: 'Franchisee Mgmt',
    description: 'Manage franchisee wallet balances, withdrawal requests, bank payouts, and reconciliation.',
    route: '/admin-panel/solar-shop/reseller-management/wallet',
    primaryAction: 'Manage Settlements',
    icon: 'FaWallet',
    isRegional: false,
    badge: 'Payouts',
    keywords: ['earnings & settlement', 'wallet', 'settlement', 'payouts', 'withdrawals', 'franchisee management'],
  },
  {
    id: 'fm-agreements',
    title: 'Agreement Settings',
    category: 'franchisee',
    categoryLabel: 'Franchisee Mgmt',
    description: 'Configure legal agreement templates, tenure rules, and digital signature terms for franchisees.',
    route: '/admin-panel/solar-shop/reseller-management/settings',
    primaryAction: 'Agreement Settings',
    icon: 'FiFileText',
    isRegional: false,
    badge: 'Legal & Terms',
    keywords: ['agreement settings', 'contract', 'franchisee settings', 'legal', 'tenure', 'franchisee management'],
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 5. SOLARSHOP: EPC QUOTE MANAGEMENT & KNOW MY MARGIN
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'qm-quote-settings',
    title: 'Quote Settings',
    category: 'margin-quotes',
    categoryLabel: 'Margins & Quotes',
    description: 'Configure EPC quotation formulas, standard proposal templates, and pricing validity.',
    route: '/admin-panel/solar-shop/quote-settings',
    primaryAction: 'Configure Quotes',
    icon: 'FiSettings',
    isRegional: false,
    badge: 'Quote Rules',
    keywords: ['quote settings', 'epc quote management', 'quotation', 'proposals', 'pricing'],
  },
  {
    id: 'qm-warranties',
    title: 'Warranty Options',
    category: 'margin-quotes',
    categoryLabel: 'Margins & Quotes',
    description: 'Configure standard and extended warranty tiers for panels, inverters, and workmanship.',
    route: '/admin-panel/solar-shop/quote-settings/warranties',
    primaryAction: 'Manage Warranties',
    icon: 'FiShield',
    isRegional: false,
    badge: 'Warranty Plans',
    keywords: ['warranty options', 'warranties', 'extended warranty', 'guarantee', 'epc quote management'],
  },
  {
    id: 'qm-analytics',
    title: 'Quote Analytics',
    category: 'margin-quotes',
    categoryLabel: 'Margins & Quotes',
    description: 'Analyze EPC quotation win rates, average deal sizes, and proposal conversion trends.',
    route: '/admin-panel/solar-shop/quote-settings/analytics',
    primaryAction: 'View Analytics',
    icon: 'FiBarChart2',
    isRegional: true,
    regionalContextHint: 'Analyze quote conversion by State and District.',
    badge: 'Quote Analytics',
    keywords: ['quote analytics', 'conversion', 'proposal analytics', 'epc quote management'],
  },
  {
    id: 'kmm-bom-settings',
    title: 'Project BOM Settings',
    category: 'margin-quotes',
    categoryLabel: 'Margins & Quotes',
    description: 'Configure Project Bill of Materials (BOM) components, hardware rules, and labor estimates.',
    route: '/admin-panel/solar-shop/project-bom-settings',
    primaryAction: 'Configure BOM',
    icon: 'FiSliders',
    isRegional: false,
    badge: 'BOM Master',
    keywords: ['project bom settings', 'know my margin', 'kmm', 'bom', 'materials', 'costing'],
  },
  {
    id: 'kmm-estimator-settings',
    title: 'Estimator Settings',
    category: 'margin-quotes',
    categoryLabel: 'Margins & Quotes',
    description: 'Configure Know My Margin (KMM) margin calculation formulas, labor constants, and profit thresholds.',
    route: '/admin-panel/solar-shop/estimator-settings',
    primaryAction: 'Configure Estimator',
    icon: 'FiSettings',
    isRegional: false,
    badge: 'Margin Estimator',
    keywords: ['estimator settings', 'know my margin', 'kmm', 'margin estimator', 'profit formula'],
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 6. BDE MANAGEMENT & SALES TEAMS
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'bde-create',
    title: 'Create BDE',
    category: 'bde',
    categoryLabel: 'BDE Management',
    description: 'Onboard a new Business Development Executive with profile, login credentials, and initial roles.',
    route: '/admin-panel/bde-management/create',
    primaryAction: 'Create New BDE',
    icon: 'FaUserPlus',
    isRegional: false,
    badge: 'Onboarding',
    keywords: ['bde', 'create', 'add', 'onboard', 'user', 'sales executive', 'credentials'],
  },
  {
    id: 'bde-territory',
    title: 'Territory Assignment',
    category: 'bde',
    categoryLabel: 'BDE Management',
    description: 'Assign States, Districts, and specific Clusters/Territories to active BDEs.',
    route: '/admin-panel/bde-management/territory-assignment',
    primaryAction: 'Assign Territories',
    icon: 'FaMapLocationDot',
    isRegional: true,
    regionalContextHint: 'Territory allocation is defined per State and District.',
    badge: 'Regional Allocation',
    keywords: ['territory', 'bde', 'assign', 'state', 'district', 'cluster', 'region', 'allocation'],
  },
  {
    id: 'bde-goals',
    title: 'Goal Assignment',
    category: 'bde',
    categoryLabel: 'BDE Management',
    description: 'Set monthly and quarterly sales, revenue, and franchisee onboarding targets for BDEs.',
    route: '/admin-panel/bde-management/goal-assignment',
    primaryAction: 'Set BDE Goals',
    icon: 'FaCoins',
    isRegional: false,
    badge: 'Targets',
    keywords: ['goals', 'targets', 'bde', 'quota', 'kpi', 'revenue', 'commission'],
  },
  {
    id: 'bde-exceptions',
    title: 'Territory Exceptions',
    category: 'bde',
    categoryLabel: 'BDE Management',
    description: 'Manage cross-territory exceptions and special coverage permissions for BDEs.',
    route: '/admin-panel/bde-management/territory-exceptions',
    primaryAction: 'Manage Exceptions',
    icon: 'FaMapLocationDot',
    isRegional: true,
    regionalContextHint: 'Exceptions allow BDEs to operate outside default assigned districts.',
    badge: 'Regional Exception',
    keywords: ['territory', 'exception', 'override', 'bde', 'district', 'cross-territory'],
  },
  {
    id: 'bde-directory',
    title: 'All BDEs Directory',
    category: 'bde',
    categoryLabel: 'BDE Management',
    description: 'Directory of all active, suspended, and pending BDEs with full profile and performance view.',
    route: '/admin-panel/bde-management/all',
    primaryAction: 'View All BDEs',
    icon: 'FaUsers',
    isRegional: true,
    regionalContextHint: 'Filter BDEs assigned to specific states and districts.',
    badge: 'Management',
    keywords: ['bde', 'list', 'directory', 'all', 'executives', 'sales team', 'users'],
  },
  {
    id: 'bde-funnel',
    title: 'Conversion Funnel',
    category: 'bde',
    categoryLabel: 'BDE Management',
    description: 'Track lead conversion stages, franchisee acquisition pipeline, and conversion velocity.',
    route: '/admin-panel/bde-management/conversion-funnel',
    primaryAction: 'View Funnel',
    icon: 'FaCoins',
    isRegional: false,
    badge: 'Pipeline Analytics',
    keywords: ['funnel', 'conversion', 'pipeline', 'bde', 'leads', 'acquisition'],
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 7. SOLARKITS PLATFORM & CORE PRODUCT CONFIGURATIONS
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'sk-catalog',
    title: 'Solar Kits Catalog',
    category: 'solarkits',
    categoryLabel: 'SolarKits Core',
    description: 'Configure standard and customized Solar Kits, bill of materials (BOM), and specifications.',
    route: '/admin-panel/product-configurations/solar-kits',
    primaryAction: 'Manage Solar Kits',
    icon: 'HiCube',
    isRegional: false,
    badge: 'Core Catalog',
    keywords: ['solar kits', 'kits', 'catalog', 'bom', 'components', 'solar', 'system'],
  },
  {
    id: 'sk-project-types',
    title: 'Project Types',
    category: 'solarkits',
    categoryLabel: 'SolarKits Core',
    description: 'Define and configure project classifications (Residential, Commercial, Industrial, Agricultural).',
    route: '/admin-panel/product-configurations/project-types',
    primaryAction: 'Configure Types',
    icon: 'GoProject',
    isRegional: false,
    badge: 'Taxonomy',
    keywords: ['project types', 'category', 'residential', 'commercial', 'industrial', 'agricultural'],
  },
  {
    id: 'sk-templates',
    title: 'Product Templates',
    category: 'solarkits',
    categoryLabel: 'SolarKits Core',
    description: 'Setup reusable product templates and predefined component configurations for quick kit creation.',
    route: '/admin-panel/product-configurations/product-templates',
    primaryAction: 'Manage Templates',
    icon: 'HiOutlineTemplate',
    isRegional: false,
    badge: 'Templates',
    keywords: ['templates', 'product', 'presets', 'reusable', 'blueprint'],
  },
  {
    id: 'sk-sku-master',
    title: 'SKU Master',
    category: 'solarkits',
    categoryLabel: 'SolarKits Core',
    description: 'Central SKU repository for solar panels, inverters, structures, cables, and BOS accessories.',
    route: '/admin-panel/product-configurations/sku-master',
    primaryAction: 'Configure SKUs',
    icon: 'MdQrCode2',
    isRegional: false,
    badge: 'Inventory Master',
    keywords: ['sku', 'master', 'catalog', 'parts', 'items', 'inverters', 'panels', 'accessories'],
  },
  {
    id: 'sk-units',
    title: 'Units Management',
    category: 'solarkits',
    categoryLabel: 'SolarKits Core',
    description: 'Define measurement units (kW, MW, Watts, Meters, Nos, Sets) for products and pricing.',
    route: '/admin-panel/product-configurations/units-management',
    primaryAction: 'Manage Units',
    icon: 'FaRulerCombined',
    isRegional: false,
    badge: 'Standards',
    keywords: ['units', 'measurement', 'kw', 'watts', 'meters', 'dimensions'],
  },
  {
    id: 'sk-price-master',
    title: 'Benchmark Price Master',
    category: 'solarkits',
    categoryLabel: 'SolarKits Core',
    description: 'Set benchmark market prices, state-level base pricing, and baseline cost calculations.',
    route: '/admin-panel/product-configurations/price-master',
    primaryAction: 'Set Benchmark Prices',
    icon: 'FaCoins',
    isRegional: true,
    regionalContextHint: 'Benchmark prices can be tuned based on state tax and logistics variations.',
    badge: 'Regional Pricing',
    keywords: ['price', 'pricing', 'benchmark', 'master', 'rate', 'cost', 'state pricing'],
  },
  {
    id: 'sk-price-requests',
    title: 'Price Requests',
    category: 'solarkits',
    categoryLabel: 'SolarKits Core',
    description: 'Review and approve custom pricing requests submitted by sales agents and EPC contractors.',
    route: '/admin-panel/product-configurations/price-requests',
    primaryAction: 'Review Requests',
    icon: 'FaCoins',
    isRegional: false,
    badge: 'Approvals',
    keywords: ['price requests', 'discounts', 'special pricing', 'approval', 'epc requests'],
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 8. LOCATION, CLUSTERS & LOGISTICS INFRASTRUCTURE
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'loc-setup',
    title: 'Setup Location (States & Districts)',
    category: 'location',
    categoryLabel: 'Location & Clusters',
    description: 'Enable or disable operative States and Districts across India for business expansion.',
    route: '/admin-panel/settings/location-setting/setup-location',
    primaryAction: 'Enable States & Districts',
    icon: 'FaMapLocationDot',
    isRegional: true,
    regionalContextHint: 'Primary control to activate or deactivate business operations in any State/District.',
    badge: 'Regional Core',
    keywords: ['location', 'states', 'districts', 'setup', 'enable state', 'activate district'],
  },
  {
    id: 'loc-clusters',
    title: 'Cluster Setup',
    category: 'location',
    categoryLabel: 'Location & Clusters',
    description: 'Group multiple districts into operational Clusters for regional sales and logistics management.',
    route: '/admin-panel/settings/location-setting/cluster-setup',
    primaryAction: 'Configure Clusters',
    icon: 'BiSolidLayerPlus',
    isRegional: true,
    regionalContextHint: 'Clusters organize districts within a state under single leadership.',
    badge: 'Regional Core',
    keywords: ['clusters', 'cluster setup', 'districts grouping', 'regional zones'],
  },
  {
    id: 'loc-overview',
    title: 'Location Overview & Geo Map',
    category: 'location',
    categoryLabel: 'Location & Clusters',
    description: 'High-level geographic overview of all enabled states, operative districts, and cluster boundaries.',
    route: '/admin-panel/settings/location-setting/location-overview',
    primaryAction: 'View Location Map',
    icon: 'FaMagnifyingGlassLocation',
    isRegional: true,
    regionalContextHint: 'Visualizes active state coverage across India.',
    badge: 'Regional Core',
    keywords: ['location overview', 'geo map', 'coverage', 'active states', 'territory map'],
  },
  {
    id: 'log-warehouses',
    title: 'Company Warehouses',
    category: 'location',
    categoryLabel: 'Location & Clusters',
    description: 'Configure company-owned and partner warehouses, storage capacities, and servicing states.',
    route: '/admin-panel/operations/company-warehouses',
    primaryAction: 'Configure Warehouses',
    icon: 'MdWarehouse',
    isRegional: true,
    regionalContextHint: 'Warehouses are located in specific states and service neighboring districts.',
    badge: 'Regional Hub',
    keywords: ['warehouse', 'storage', 'depot', 'state', 'inventory hub', 'operations'],
  },
  {
    id: 'log-mfg-brands',
    title: 'Manufacturing Brands',
    category: 'location',
    categoryLabel: 'Location & Clusters',
    description: 'Manage solar module and inverter brand manufacturers, OEM partners, and tier rankings.',
    route: '/admin-panel/operations/manufacturing-brands',
    primaryAction: 'Configure Brands',
    icon: 'FaIndustry',
    isRegional: false,
    badge: 'OEM Partners',
    keywords: ['brands', 'manufacturers', 'oem', 'tier 1', 'solar panels', 'inverters'],
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 9. SYSTEM SETTINGS, RBAC & WEBSITES
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'sys-rbac',
    title: 'Role-Based Access Control (RBAC)',
    category: 'system',
    categoryLabel: 'System & RBAC',
    description: 'Configure administrative roles, granular module permissions, view/edit/delete entitlements.',
    route: '/admin-panel/settings/role-settings/role-based-access-control',
    primaryAction: 'Manage Roles',
    icon: 'FaUserShield',
    isRegional: false,
    badge: 'Security',
    keywords: ['rbac', 'roles', 'permissions', 'access control', 'security', 'privileges'],
  },
  {
    id: 'sys-departments',
    title: 'Departments Management',
    category: 'system',
    categoryLabel: 'System & RBAC',
    description: 'Setup company departments (Sales, Technical, Operations, Logistics, Accounts, HR).',
    route: '/admin-panel/settings/role-settings/departments',
    primaryAction: 'Configure Departments',
    icon: 'MdAccountTree',
    isRegional: false,
    badge: 'Organization',
    keywords: ['departments', 'teams', 'org chart', 'structure'],
  },
  {
    id: 'sys-incharge',
    title: 'Temporary Incharge Setting',
    category: 'system',
    categoryLabel: 'System & RBAC',
    description: 'Delegate temporary managerial authority and approval permissions during leave or absence.',
    route: '/admin-panel/settings/hr-settings/temporary-incharge-setting',
    primaryAction: 'Assign Incharge',
    icon: 'FaUserTie',
    isRegional: false,
    badge: 'HR Governance',
    keywords: ['incharge', 'delegation', 'temporary', 'approval authority', 'hr'],
  },
  {
    id: 'sys-websites',
    title: 'Website Configurations',
    category: 'system',
    categoryLabel: 'System & RBAC',
    description: 'Manage landing pages, hero banners, and brand configurations for SolarKits and Franchise sites.',
    route: '/admin-panel/website-configurations',
    primaryAction: 'Configure Websites',
    icon: 'FaGlobe',
    isRegional: false,
    badge: 'Websites',
    keywords: ['website', 'cms', 'solar kits site', 'franchise site', 'solar store', 'banners'],
  },
  {
    id: 'sys-cms',
    title: 'Industry CMS & Types',
    category: 'system',
    categoryLabel: 'System & RBAC',
    description: 'Manage industry content, sector case studies, and application taxonomies (Agriculture, EV, etc.).',
    route: '/admin-panel/industry-content/cms',
    primaryAction: 'Manage Industry CMS',
    icon: 'FaIndustry',
    isRegional: false,
    badge: 'Content CMS',
    keywords: ['cms', 'industry content', 'case studies', 'solar sectors', 'agriculture solar'],
  },
];
