import React, { useState, useEffect } from 'react';
import { 
  TrendingUp, 
  RotateCw, 
  Filter, 
  CheckCircle2, 
  Users, 
  Zap, 
  AlertTriangle,
  ArrowDown
} from 'lucide-react';
import { bdeApi } from '../../../api/bdeApi';

export default function BdeConversionFunnel({ moduleUniqueId = 'ADM_BDE_MGMT' }) {
  const [funnelData, setFunnelData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [bdes, setBdes] = useState([]);
  const [selectedBde, setSelectedBde] = useState('');

  const fetchBdes = async () => {
    try {
      const res = await bdeApi.listBdes({ limit: 100 }, moduleUniqueId);
      if (res?.status === 'success') {
        setBdes(res.data?.bdes || res.data || []);
      }
    } catch (err) {
      console.error('Failed to load BDEs', err);
    }
  };

  const fetchFunnel = async () => {
    setLoading(true);
    try {
      const params = {};
      if (selectedBde) params.bde_id = selectedBde;
      const res = await bdeApi.getConversionFunnel(params, moduleUniqueId);
      if (res?.status === 'success') {
        setFunnelData(res.data);
      }
    } catch (err) {
      console.error('Failed to load conversion funnel', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchBdes();
  }, []);

  useEffect(() => {
    fetchFunnel();
  }, [selectedBde]);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <RotateCw className="w-8 h-8 text-amber-500 animate-spin" />
      </div>
    );
  }

  const stages = funnelData?.stages || [];
  const outcomes = funnelData?.outcomes || {};

  return (
    <div className="space-y-6">
      {/* Header & Filter */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-900 flex items-center gap-2">
            <TrendingUp className="w-5 h-5 text-amber-600" />
            BDE Onboarding Conversion Funnel
          </h2>
          <p className="text-xs text-slate-500 mt-0.5">
            Stage-by-stage conversion analytics from lead generation to fee payment and operational launch
          </p>
        </div>

        <div className="flex items-center gap-2">
          <select
            value={selectedBde}
            onChange={(e) => setSelectedBde(e.target.value)}
            className="px-3 py-1.5 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-700 focus:outline-none focus:border-amber-500"
          >
            <option value="">All BDE Officers (Network Wide)</option>
            {bdes.map((b) => (
              <option key={b._id || b.id} value={b._id || b.id}>
                {b.full_name} ({b.bde_id})
              </option>
            ))}
          </select>

          <button
            onClick={fetchFunnel}
            className="p-2 bg-slate-100 hover:bg-slate-200 text-slate-600 rounded-xl"
          >
            <RotateCw className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Outcome Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <div className="p-4.5 bg-white border border-slate-200 rounded-2xl shadow-sm">
          <span className="text-xs text-slate-500 font-semibold">Total Pipeline Leads</span>
          <div className="text-2xl font-black text-slate-900 mt-1">{funnelData?.total_leads || 0}</div>
          <span className="text-[11px] text-slate-400 mt-0.5 block">Generated by field team</span>
        </div>

        <div className="p-4.5 bg-white border border-slate-200 rounded-2xl shadow-sm">
          <span className="text-xs text-slate-500 font-semibold">Converted Partners</span>
          <div className="text-2xl font-black text-emerald-600 mt-1">{outcomes.converted || 0}</div>
          <span className="text-[11px] text-emerald-600 font-semibold mt-0.5 block">Fee paid & onboarded</span>
        </div>

        <div className="p-4.5 bg-white border border-slate-200 rounded-2xl shadow-sm">
          <span className="text-xs text-slate-500 font-semibold">Active Pipeline</span>
          <div className="text-2xl font-black text-amber-600 mt-1">{outcomes.active_pipeline || 0}</div>
          <span className="text-[11px] text-amber-600 font-semibold mt-0.5 block">Under qualification</span>
        </div>

        <div className="p-4.5 bg-white border border-slate-200 rounded-2xl shadow-sm">
          <span className="text-xs text-slate-500 font-semibold">Lost / Rejected</span>
          <div className="text-2xl font-black text-rose-600 mt-1">{(outcomes.lost || 0) + (outcomes.rejected || 0)}</div>
          <span className="text-[11px] text-rose-500 font-medium mt-0.5 block">{outcomes.lost || 0} lost, {outcomes.rejected || 0} rejected</span>
        </div>
      </div>

      {/* Visual Funnel */}
      <div className="p-6 bg-white border border-slate-200 rounded-3xl space-y-4 shadow-sm">
        <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider">Conversion Stages</h3>

        <div className="space-y-3 max-w-4xl mx-auto pt-2">
          {stages.map((st, idx) => {
            const isLast = idx === stages.length - 1;
            const colors = [
              'from-blue-500 to-blue-600',
              'from-indigo-500 to-indigo-600',
              'from-purple-500 to-purple-600',
              'from-amber-500 to-amber-600',
              'from-teal-500 to-teal-600',
              'from-cyan-500 to-cyan-600',
              'from-emerald-500 to-emerald-600',
            ];
            const bgGradient = colors[idx % colors.length];

            return (
              <div key={idx} className="space-y-1.5">
                <div className="flex items-center justify-between text-xs font-semibold text-slate-700 px-2">
                  <span className="flex items-center gap-2">
                    <span className="w-5 h-5 rounded-full bg-slate-100 text-slate-800 text-[11px] flex items-center justify-center font-bold">
                      {idx + 1}
                    </span>
                    {st.stage}
                  </span>
                  <div className="flex items-center gap-3">
                    <span className="text-slate-900 font-bold">{st.count} prospects</span>
                    <span className="text-amber-600 font-mono font-bold">({st.conversion_pct}%)</span>
                  </div>
                </div>

                <div className="w-full bg-slate-100 rounded-xl h-7 overflow-hidden p-1 border border-slate-200">
                  <div
                    className={`h-full rounded-lg bg-gradient-to-r ${bgGradient} transition-all duration-500 flex items-center justify-end px-3 shadow-sm`}
                    style={{ width: `${Math.max(12, st.conversion_pct)}%` }}
                  >
                    <span className="text-[11px] font-bold text-white drop-shadow">
                      {st.conversion_pct}%
                    </span>
                  </div>
                </div>

                {!isLast && (
                  <div className="flex justify-center py-0.5">
                    <ArrowDown className="w-3.5 h-3.5 text-slate-400" />
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
